# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.117
neo_version_range=[21.1.117,)
loader_version_range=[1,)

gottschcore_version=2.7.0
gottschcore_version_range=[2.7.0,3.0.0)

treasure2_version=5.0.3
treasure2_version_range=[5.0.0,)

curios_version=9.5.1+1.21.1
curios_version_range=[9.0.0,)

patchouli_version=1.21.1-93-NEOFORGE

mod_id=magictreasures
mod_name=Magic Treasures
mod_license=GNU GPL v3
mod_version=1.3.2
mod_group_id=gottsch
mod_authors=gottsch
mod_description=
archives_base_name=magictreasures-neoforge-1.21.1
